---
x-cli-config: &cli
  image: argon-cli:dev
  build:
    context: ../..
    dockerfile: nodejs.Dockerfile
  working_dir: /app
  restart: on-failure
  environment:
    - MAINCHAIN_URL=${MAINCHAIN_URL:-ws://archive-node:9944}

services:
  miner-1-setup:
    <<: *cli
    command: accounts create --path=/accounts/bob.json --register-keys-to=http://miner-1:9944 --account-suri=//Bob -s=0-99
    depends_on:
      miner-1:
        condition: service_healthy
    volumes:
      - miner1-data:/accounts
    restart: no
  miner-1-bidder:
    <<: *cli
    command: mining bid --env=/accounts/bob.json --max-bid=0.5 --run-continuous
    depends_on:
      miner-1-setup:
        condition: service_completed_successfully
    volumes:
      - miner1-data:/accounts
  miner-2-setup:
    <<: *cli
    command: accounts create --path=/accounts/dave.json --register-keys-to=http://miner-2:9944 --account-suri=//Dave -s=0-49
    depends_on:
      miner-2:
        condition: service_healthy
    volumes:
      - miner2-data:/accounts
    restart: no
  miner-2-bidder:
    <<: *cli
    command: mining bid --env=/accounts/dave.json --max-bid=2 --max-seats=5 --bid-delay=2 --run-continuous
    depends_on:
      miner-2-setup:
        condition: service_completed_successfully
    volumes:
      - miner2-data:/accounts

volumes:
  miner1-data:
  miner2-data:
